/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ckt_eirot_opencv4jni_GrayProcess */

#ifndef _Included_com_ckt_eirot_opencv4jni_GrayProcess
#define _Included_com_ckt_eirot_opencv4jni_GrayProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ckt_eirot_opencv4jni_GrayProcess
 * Method:    grayProcess
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_ckt_eirot_opencv4jni_GrayProcess_grayProcess
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
